package projects;

public enum Preference {
    WORK_EARLIER_PEFERENCE_ACC,
    WORK_EARLIER_PEFERENCE_NO_ACC,
    WORK_STANDART,
    WORK_FROM_HOME_PREFERENCE_ACC,
    WORK_EARLIER_PEFERENCE_ENG,
    WORK_EARLIER_PEFERENCE_NO_ENG,
    WORK_FROM_HOME_PREFERENCE_ENG,
    WORK_EARLIER_PEFERENCE_LAW,
    WORK_EARLIER_PEFERENCE_NO_LAW,
    WORK_FROM_HOME_PREFERENCE_LAW
}
